image_paths = {
    0: {"name": "Сборщик эликсира", "data": ["static/images/0.jpg", "static/images/0_1.jpg"]},
    1: {"name": "GitVerse User", "data": ["static/images/1.jpg"]},
    2: {"name": "C++ Builder", "data": ["static/images/2.jpg"]},
    3: {"name": "Зондби ферма", "data": ["static/images/3.jpg"]},
    4: {"name": "Спекулянт", "data": ["static/images/4.jpg", "static/images/4_1.jpg"]},
    5: {"name": "Король кайфа", "data": ["static/images/5.jpg", "static/images/5_1.jpg"]},
    6: {"name": "Солана минтер", "data": ["static/images/6.jpg"]},
    7: {"name": "Дед инсайд", "data": ["static/images/7.jpg"]},
    8: {"name": "Умру за кек", "data": ["static/images/8.jpg", "static/images/8_1.jpg", "static/images/8_2.jpg", "static/images/8_3.jpg", "static/images/8_4.jpg"]},
    9: {"name": "Спермий", "data": ["static/images/9.jpg", "static/images/9_1.jpg", "static/images/9_2.jpg"]},
    10: {"name": "В NAVI", "data": ["static/images/10.jpg", "static/images/10_1.jpg"]},
    11: {"name": "Русский", "data": ["static/images/11.jpg"]},
    12: {"name": "Джедай", "data": ["static/images/12.jpg"]},
    13: {"name": "Бобка", "data": ["static/images/13.jpg", "static/images/13_1.jpg", "static/images/13_2.jpg", "static/images/13_3.jpg", "static/images/13_4.jpg", "static/images/13_5.jpg"]},
    14: {"name": "Дэб", "data": ["static/images/14.jpg", "static/images/14_1.jpg"]},
    15: {"name": "Хома", "data": ["static/images/15.jpg"]},
    16: {"name": "Панк", "data": ["static/images/16.jpg", "static/images/16_1.jpg", "static/images/16_2.jpg", "static/images/16_3.jpg", "static/images/16_4.jpg", "static/images/16_5.jpg"]},
    17: {"name": "Рыбак", "data": ["static/images/17.jpg"]},
    18: {"name": "Channel Moderator", "data": ["static/images/18.jpg"]},
    19: {"name": "Оверклокер", "data": ["static/images/19.jpg", "static/images/19_1.jpg"]},
    20: {"name": "7-8", "data": ["static/images/20.jpg", "static/images/20_1.jpg", "static/images/20_2.jpg", "static/images/20_3.jpg"]},
    21: {"name": "Нептун", "data": ["static/images/21.jpg", "static/images/21_1.jpg"]},
    22: {"name": "Indian", "data": ["static/images/22.jpg"]},
    23: {"name": "Старость", "data": ["static/images/23.jpg", "static/images/23.jpg"]},
    24: {"name": "Тотем бессмертия", "data": ["static/images/24.jpg"]},
    25: {"name": "Смартфон Vivo", "data": ["static/images/25.jpg"]},
    26: {"name": "Водолаз", "data": ["static/images/26.jpg", "static/images/26_1.jpg", "static/images/26_2.jpg"]},
    27: {"name": "Имшшка фреде", "data": ["static/images/27.jpg"]},
    28: {"name": "Вор", "data": ["static/images/28.jpg", "static/images/28_1.jpg"]},
    29: {"name": "Тренер по плаванию", "data": ["static/images/29.jpg"]},
    30: {"name": "Волосок", "data": ["static/images/30.jpg"]},
}